### ISSUE TITLE
Takin Ya With Me 

### ISSUE THREAD

**Issue by Huffster** [townteki/townsquare#1077]
**Card**

Takin Ya With Me 

**Describe the bug**
The react didn’t trigger when discarding a token dude.

**To Reproduce**
1. Do action '...'
3. Start shootout '....'

**Screenshots**

**Additional context**

**Comment by mmeldo** [comment]
Tested with the token dude and react triggered just fine. Without any more information, I cannot reproduce. 
Next time, please provide more information. The screenshot of both posses would be really helpful here.

**Comment by mmeldo** [comment]
Not able to work on this without further details. Will be reopened in case they are provided.
