### ISSUE TITLE
Lost to the Plague cannot be attached

### ISSUE THREAD

**Issue by mmeldo** [townteki/townsquare#1175]
Submitter: Greg Melnyk (Deputy_Melnyk)
Lost to the Plague cannot be attached.  Our workaround was to move it to boot hill and remember that it was attached to a dude.  Then I moved it to the discard pile when the opposing dude left play.

**Comment by gmelnyk** [comment]
Lost to the Plague is not attachable via manual command.

**Comment by mmeldo** [comment]
> Lost to the Plague is not attachable via manual command.

@gmelnyk Can you please give more details? I just tested it and when I had `Lost to the Plague` in hand, typed `/attach` command in chat, then clicked on the `Lost to the Plague` to select it and then clicked on opponent dude, it was attached.

**Comment by gmelnyk** [comment]
Ah, I was attempting to /use first.  I will try attach without use next time.

Thanks,
Greg

Sent from Outlook<https://aka.ms/qtex0l> for iOS

________________________________

**Comment by mmeldo** [comment]
Actually, there is a small problem that cards from "being played" pile cannot be chosen for attach command.

**Comment by mmeldo** [comment]
@gmelnyk I fixed the `/attach` command to be able to choose also from "being played" pile. That means you can keep using it the same (correct) way - first `/use` then `/attach`
