### ISSUE TITLE
Incorrect player in the Sundown discard message

### ISSUE THREAD

**Issue by mmeldo** [townteki/townsquare#1275]
Submitter: Greg Melnyk
I discarded a Clint Ramsey at Sundown, but the chat log showed my opponent doing that instead of me.  I grabbed a screenshot.

**Comment by gmelnyk** [comment]
![Doomtown Chat Log Error](https://user-images.githubusercontent.com/49254272/142742136-abeb4ca0-4b75-405f-8a17-202d0d3ca4ea.png)

**Comment by mmeldo** [comment]
it is possible the same problem happens also in Upkeep prompt where sometimes dudes with upkeep are not highlighted. That can be cause by incorrect player doing the highlighting.
