### ISSUE TITLE
Joker non targetable for discard when The Fourth Ring ability triggers

### ISSUE THREAD

**Issue by janosikm** [townteki/townsquare#136]
This is likely more general, but it was reproduced with The Fourth Ring outfit. 
When ability triggers, you are able to select cards in your play hand for discard, however except the Joker which is grayed out.

**Comment by AaronSchnabel** [comment]
This is definitely more general, seems to apply to any discard effect. I've used Philip Swinford's ability, as well as my work on The Winning Agenda to verify that Jokers are not selectable to discard from the play hand.
