### ISSUE TITLE
The Mixer's target not showing up in chat

### ISSUE THREAD

**Issue by TheRealEntrican** [townteki/townsquare#1361]
**Card**
The Mixer

**Describe the bug**
Very minor, but when the mixer was used it didn't show his target in the chat, so my opponent couldn't tell who I used the ability on. 

**To Reproduce**
1. Do action '...'
3. Start shootout '....'

**Screenshots**

**Additional context**

**Comment by sholder** [comment]
Note: this issue appears to be fixed already

**Comment by mmeldo** [comment]
Yeah, I put there a fix among others and forgot to close the issue.
