### ISSUE TITLE
Smiling frog interaction with joker

### ISSUE THREAD

**Issue by TheRealEntrican** [townteki/townsquare#1403]
**Card**
Smiling frog

**Describe the bug**
Very minor issue, but when using smiling frog's ability and discarding a joker, the game does not give you the option of choosing a suit and therefore you cannot make the joker a heart to give +2 bullets instead of +1. 

**To Reproduce**
1. Do action '...'
3. Start shootout '....'

**Screenshots**

**Additional context**

**Comment by mmeldo** [comment]
Are we sure that player can select a suit when discarding for the Smiling Frog? I thought you can select only when using joker for draw hands and pulls.

**Comment by TheRealEntrican** [comment]
You are correct, I asked the discord and they confirmed you can't select the suit outside of draw hands and pulls. Thanks!
