### ISSUE TITLE
Ghostly Communion

### ISSUE THREAD

**Issue by Huffster** [townteki/townsquare#1433]
**Card**
Ghostly Communion

**Describe the bug**
Tried to use Ghostly Communion while my dude was at an OOT deed.  It did not allow me to move them to TS.  Because my home is seen as a Holy Ground while casting the spell it should be allowed. 

**To Reproduce**
1. Do action '...'
3. Start shootout '....'

**Screenshots**

**Additional context**

**Comment by stopfstedt** [comment]
i reviewed the current implementation, and it seems to work as intended. perhaps the deck included the [original card](https://dtdb.co/en/card/17017), which will exclude the townsquare if no holy ground locations are in town.

can you confirm?

**Comment by Huffster** [comment]
I checked all of my deck builds and they use the WWE version.
Were you using Black Hills Guardians as your home?
I was using The Spiritual Society, which gains the Holy Ground keyword when Ghostly Communion triggers.


Ricky Huff (he/him/his)
Senior Mechanical Engineering Technical Lead

Synapse Product Development
Part of Capgemini Invent
mail 1511 6th Ave Suite 260, Seattle, WA 98101
direct +1 206 832 1269 ext. 4626<tel:+1%20206%20832%201269,4626> | office +1 206 381 0898<tel:+1%20206%20381%200898> | mobile +1 760 953 0069<tel:+1%20760%20953%200069>
***@***.******@***.***> | https://www.synapse.com<https://www.synapse.com/>

This email and any files transmitted with it are confidential. Unauthorized publication, use or dissemination of this email is prohibited.
Please consider the environment before printing.

________________________________

**Comment by stopfstedt** [comment]
> I checked all of my deck builds and they use the WWE version. Were you using Black Hills Guardians as your home? I was using The Spiritual Society, which gains the Holy Ground keyword when Ghostly Communion triggers.

Yea, that was my bad. i didn't realize that the home i was using already had the printed "Holy Ground" keyword (Gateway to Beyond . once I realized my blunder, i switched the home to "Spiritual Society" and was able to reproduce the bug. 
I am able to reproduce it now.
