### ISSUE TITLE
Draw hand changers don't look at phases when resolving jokers

### ISSUE THREAD

**Issue by PesiTheWizard** [townteki/townsquare#1464]
Any card that invokes .determineHandResult has predetermined joker behaviour

The clearest examples:
* Using Devil's Six Gun during lowball has it maximize the rank
* Bad Beat and Bottom Dealin' always minimize the rank regardless of phase or who owns the joker

(There might be deeper issues when several of these intersect)

**Comment by mmeldo** [comment]
Fixed by #1502
