### ISSUE TITLE
Black Owl Shootout Ability

### ISSUE THREAD

**Issue by shosuro006** [townteki/townsquare#1549]
**Card**
Black Owl

**Describe the bug**
When Black Owl uses his shootout ability to force an opposing dude to be the first casualty, the game locks up after taking the first casualty with the targeted dude.

Was not able to replicate if only 1 casualty was taken.

**To Reproduce**
1. Do action 'Black Owl shootout vs opponent'
2. Opponent loses shootout by more than 3 ranks.
3. Opponent takes casualty with the card Black Owl targetted. Doesnt matter if you ace, discard, or send home. The Casualty pop up prompt locks and does not allow the game to progress.

**Screenshots**

**Additional context**
![blackowl fail](https://user-images.githubusercontent.com/114325083/204106145-c85123e1-7d9b-4ebe-844a-1e47ad12d30c.png)

**Comment by mmeldo** [comment]
Was this the same game as the Land Purchase error? Because that can cause unpredictable behavior. I am mentioning this because I was not able to reproduce.

**Comment by mmeldo** [comment]
Based on my testing, this is probably caused by issue #1548 because after this happens, game is really unstable and prompts can get locked.
