### ISSUE TITLE
Request to Verify Account, no email received.

### ISSUE THREAD

**Issue by DrtyByt** [townteki/townsquare#1557]
I got the email on the newsletter to try and check things out on Doomtown.online. But I've run into an issue, I tried to register, got an error about communications with the server. Now it says I'm registered, when I try, but if I try to login I get a message stating that I need to verify my account, but received no verification email. I did try a password reset, and that worked, but that didn't auto verify my account.

Options?

**Comment by mmeldo** [comment]
Hi there. I checked email deliveries and it does not seem any email was sent. Not sure what happened as other emails were delivered fine.
Anyway, your account was verified manually. Please check if your account works fine and let us know.

**Comment by DrtyByt** [comment]
Works just fine now. Thanks!
