### ISSUE TITLE
Issue with Pinned Down and/or Black Owl Shootout Ability

### ISSUE THREAD

**Issue by shosuro006** [townteki/townsquare#1562]
**Card**
Pinned Down alone or Black Owl alone.

**Describe the bug**
When taking casualties after losing a round and having been pinned down earlier, I followed the prompts to either Ace or Discard my dude. It does matter which option you choose as the issue happens on both discard or acing. If you have to take more casualties beyond what was pinned down or Black Owl'd, then the prompt remains stuck on the Pinned Down target and does not let you advance the casualties step. Happened to my opponent and it happened to me.

**To Reproduce**
1. Do action 'Pinned Down on opponent dude
2. Win or tie the shootout
3. When opponent takes casualties, the prompts force you to pick the pinned down dude as the first casualty. Follow prompts to either ace or discard the dude. Should you have more casualties to take the round get stuck and no prompt returns for you to continue acing or discarding dudes.

**Screenshots**
see below

**Additional context**
![Pinned Down Issue](https://user-images.githubusercontent.com/114325083/216854186-3a3778b3-64dd-4051-af08-a046d9281f11.png)

**Comment by mmeldo** [comment]
I tested it and was only able to reproduce it in a way that the prompt incorrectly stayed on the first casualty resolution, but it did not get stuck in a way that you could not continue without doing `/cancel-prompt`. There is still a `Done` button that will end the casualties step.
Is this the same you experienced?
