### ISSUE TITLE
IMPORTANT: CAN'T VERIFY NEW ACCOUNTS!!

### ISSUE THREAD

**Issue by metroghost** [townteki/townsquare#1573]
IMPORTANT: CAN'T VERIFY NEW ACCOUNTS!

1. NEW ACCOUNT
2. VERIFY
3. UNABLE TO VERIFY
4. CAN'T LOG IN AND CAN'T PLAY.
**Screenshots**
WHEN CLICKING ON VERIFYING URL:

![‏‏لقطة الشاشة (267)](https://user-images.githubusercontent.com/129083074/227975092-9cd5474e-a839-4ff9-8e92-a8ec59a202bc.png)

**Comment by mmeldo** [comment]
The problem with activation was resolved .. no need to shout :)
