### ISSUE TITLE
Farnum's Consortium does not give Production Bonus to a deed if you lose control of it.

### ISSUE THREAD

**Issue by Aussie-Scum** [townteki/townsquare#1580]
**Card**
Farnum's Consortium

**Describe the bug**
In town deeds  you own should have +1 Production.   If you lose control of one of those deeds, the production bonus goes away.

**To Reproduce**
1. Play Farnum's Consortium
2. Play a Deed
3. Move one of your dudes there - deed gets a Production bonus
4. Have Opponent move dude(s) there such that you lose control of the deed
5. Production bonus goes away

**Screenshots**
![Bug1](https://github.com/townteki/townsquare/assets/108785065/4998be82-7b49-4a3e-aff6-6acc40a90b0a)

See attached.

**Additional context**
Note in the example provided that the deed Gage Export Co does not have the P3 token on it.

**Comment by mmeldo** [comment]
fixed, will be deployed with next version
