### ISSUE TITLE
Mariel Lewis

### ISSUE THREAD

**Issue by Huffster** [townteki/townsquare#1594]
Mariel Lewis

My opponent tried to kidnap my dude and I resisted.
Mariel Lewis was in my posse and I had 7 inf to their 5.
I used her ability and the chat said I didn't have enough Inf.

At the time Mazatl wasn't in my posse otherwise the screen grab captures the state of the game.

**To Reproduce**
1. Do action '...'
3. Start shootout '....'

**Screenshots**

**Additional context**
![Screenshot 2023-08-27 7 35 27 AM](https://github.com/townteki/townsquare/assets/69087102/10862c43-abb5-4ef7-830a-897c089d0584)

**Comment by mmeldo** [comment]
The problem here is not the influence, but a fact that it is a job. Still a bug since it should allow you to execute the action if you are not the one running the job, and the message could be better, but just to make it clear.

**Comment by mmeldo** [comment]
fixed after next deployment
