### ISSUE TITLE
Consecration - WWE - Resolution is usable when attached to dudes outside of a shootout

### ISSUE THREAD

**Issue by shosuro006** [townteki/townsquare#1615]
**Card**
Consecration WWE

**Describe the bug**
During a shootout resolution, dude with Consecration that was not in the shootout was able to use the cheatin resolution from outside the shootout. This ability is usable during lowball, but during shootouts the dude with the spell must be in the fight.

**Comment by mmeldo** [comment]
There is already an issue for this, even though hidden as a task. Thus I created a regular one out of that #1616
