### ISSUE TITLE
Bayou Vermillion Railroad - Trait for 1GR discount of first mystical card played not working

### ISSUE THREAD

**Issue by shosuro006** [townteki/townsquare#1622]
**Card**
Bayou Vermillion + Quaterman Prime or Devil's Six Gun

**Describe the bug**
In a solo game, the 1st mystical card I played was Devil's Six gun. It was successfully invented, however the script indicated the GR cost of 3 was paid. Since my outfit is Bayou Vermillion it should have discounted that first mystical card by 1GR.

I tried to replicate the issue, created a new game. This time my first mystical card was Quaterman Prime. I paid 2GR and succeessfully invented it. This mystical card should have had a 1GR discount.

I also replicated the issue when I tried a new game and did a shopping play to bring in My Father's Cross, a non gadget mystical goods. 

**Screenshots**
![image](https://github.com/townteki/townsquare/assets/114325083/0ba67782-0872-4027-8cdd-6c3781093809)

![image](https://github.com/townteki/townsquare/assets/114325083/5b80edec-c357-47b8-86d5-26a8ceb1cb50)

**Comment by mmeldo** [comment]
Fixed in `1.1.8`
