### ISSUE TITLE
React prompt says "undefined" when Jacqueline Isham joins a marks posse

### ISSUE THREAD

**Issue by AaronSchnabel** [townteki/townsquare#189]
**Card Name**
Jacqueline Isham

**Bug Description**
When Jacqueline Isham joins a mark's posse, the prompt asking if you want to use her react says "Any reactions to undefined joining posse?"

It should say something like "Do you want to use Jacqueline Isham's react?" to clarify that it is her react ability that is available, not just any react.

**To Reproduce**
1. Accept a callout from your opponent
2. Have Jacqueline join the posse
3. Start shootout '....'

**Screenshots**
![jacqueline isham undefined](https://user-images.githubusercontent.com/6004301/111813382-5e177680-8896-11eb-9f63-b9fceac586c8.png)

**Additional context**
I believe that this same undefined message appears on other prompts, I just don't remember which card I saw it happen with. It might just be a problem with the react timing window code?

**Comment by mmeldo** [comment]
Nice bug report 👍 only if also my other customer reports were like that
