### ISSUE TITLE
Jokers cause cheatin' hands to be counted as legal

### ISSUE THREAD

**Issue by AaronSchnabel** [townteki/townsquare#202]
**Card**
Red and Black Jokers

**Describe the bug**
If you have a Joker in your draw hand, your draw hand will be counted as legal even if it's cheatin' (i.e. you have three 3 of diamonds, or two 5 of hearts)

**To Reproduce**
1. Get a draw hand
2. Have a Joker in it
3. Also have a cheatin' set of cards (2 5 of hearts, etc)
4. Your hand will be counted as legal

**Screenshots**
![draw hand](https://user-images.githubusercontent.com/6004301/112246993-c48ef280-8c10-11eb-897a-fbfd92a277ea.png)
![draw hand 2](https://user-images.githubusercontent.com/6004301/112246999-c658b600-8c10-11eb-9415-ca52d0afd4ca.png)
![hand results](https://user-images.githubusercontent.com/6004301/112247006-c789e300-8c10-11eb-90bc-d886e2906bf7.png)

**Comment by mmeldo** [comment]
I love your bug reports 😃
