### ISSUE TITLE
Feat: Take Yer Lumps casualties selection improvement

### ISSUE THREAD

**Issue by mmeldo** [townteki/townsquare#207]
Current behaviour:

User is prompted with options to "Ace", "Discard", "Send Home". They do this one by one. That results in a weird situation in case some dude has to be first casualty.

Rules:

Rules for the `Take Yer Lumps` step have been changed slightly. 
Current rules:
> Starting with the loser of the
round, players must discard or ace dudes and/or Sidekicks in their posse to satisfy their casualties. On the
rare chance the round was an absolute tie with identical draw hands, apply casualties simultaneously.

> Choose and apply your casualties one at a time.
Remember that cards attached to an aced or discarded
dude are sent to their owner’s discard pile.

> Discarding a dude in your posse covers 1 casualty,
while acing a dude in your posse covers 2. Discarding
a card in your posse with the Sidekick keyword covers
1 casualty.

> Harrowed dudes have slightly different rules for
casualties. Sending a Harrowed dude in your posse
home booted covers 1 casualty, discarding them covers
2 casualties, and acing them covers 3 casualties.

> You are required to do all that you can to suffer
all of your casualties, and you cannot choose to suffer
excess casualties! If you suffer 4 casualties and have 2
dudes in your posse, you can’t discard them (to cover
2 casualties) and then stop suffering casualties. You
must do all that you can to suffer your 4 casualties,
which in this case means acing both dudes (to cover
4 casualties).

Therefore current way the step is performed is more or less correct. What should be updated is how the first casualties are selected, and add a way to calculate possible casualties to prevent player from for example discarding when they should ace.

Also check if the Takin' Ya With Me and Shield of Faith cards work correctly with the updated casualties selection.

Another note: When 2 different things "have to be chosen as first casualty", the game just force-picks one of them.
Player should be able to choose.

**Comment by tybar** [comment]
An additional thing to eventually fix:

A dude can be selected to be discarded even if they should be required to be aced (i.e. they are the only dude in the posse and they have to cover 2 or more casualties)

**Comment by mmeldo** [comment]
Rules for the `Take Yer Lumps` step have been changed slightly. 
Current rules:
> Starting with the loser of the
round, players must discard or ace dudes and/or Sidekicks in their posse to satisfy their casualties. On the
rare chance the round was an absolute tie with identical draw hands, apply casualties simultaneously.

> Choose and apply your casualties one at a time.
Remember that cards attached to an aced or discarded
dude are sent to their owner’s discard pile.

> Discarding a dude in your posse covers 1 casualty,
while acing a dude in your posse covers 2. Discarding
a card in your posse with the Sidekick keyword covers
1 casualty.

> Harrowed dudes have slightly different rules for
casualties. Sending a Harrowed dude in your posse
home booted covers 1 casualty, discarding them covers
2 casualties, and acing them covers 3 casualties.

> You are required to do all that you can to suffer
all of your casualties, and you cannot choose to suffer
excess casualties! If you suffer 4 casualties and have 2
dudes in your posse, you can’t discard them (to cover
2 casualties) and then stop suffering casualties. You
must do all that you can to suffer your 4 casualties,
which in this case means acing both dudes (to cover
4 casualties).

**Comment by mmeldo** [comment]
Therefore current way the step is performed is more or less correct. What should be updated is how the first casualties are selected, and add a way to calculate possible casualties to prevent player from for example discarding when they should ace.
