### ISSUE TITLE
Margaret Haggerty plus The Wretched broke Ghost Rock counter

### ISSUE THREAD

**Issue by harbinger87** [townteki/townsquare#376]
**Card**
Margaret Haggerty plus two The Wretched (maybe)

**Describe the bug**
During a game a couple of days ago, I had Margaret Haggerty plus two The Wretched at my home during Upkeep-phase and 6 Ghost Rock in my stash. When I performed the Upkeep, I was prepared to manually adjust my Ghost Rock afterwards due to Margaret's ability (-1 upkeep to Gadget dudes), but something different happened. My Ghost Rock was set to zero and the variable probably broke, because no matter how often I clicked on increase or decrease Ghost Rock, I was unable to get additional Ghost Rock. The status notes in the chat window always listed my current Ghost Rock amount as empty.

**To Reproduce**
Couldn't check whether it was reproducable, but here's how it happened:
1. Have Maraget Haggerty and two The Wretched at home (home was "Bayou Vermilion Railroad"
2. Have six Ghost Rock in your stash after production
3. Pay Upkeep

**Comment by mmeldo** [comment]
Thanks for the report. There was a problem with the GR being able to go to incorrect state but that was fixed by #363 
Could you please check if the problem still persists?
