### ISSUE TITLE
Clicking on 4th Ring outfit boots or unboots it

### ISSUE THREAD

**Issue by tybar** [townteki/townsquare#410]
**The 4th Ring**
Note: this may happen with other outfits, but I have not tested thoroughly.

**Describe the bug**
If the user clicks on the 4th Ring outfit, the card boots or unboots.

**To Reproduce**
1. Start a game using the 4th Ring outfit.
2. Click on The 4Th Ring at any time in the game.

Observed Behavior: The card boots or unboots, depending on its current state. Nothing else appears to happen.

**Comment by mmeldo** [comment]
This remained from the throneteki code where they have default action for clicking. Should be removed as in out case, we need menu and to have booting on click is not intuitive. Therefore the default action should be removed and menu should be shown every time there is some item.
