### ISSUE TITLE
Shadow Walk can be used to stay in the same location

### ISSUE THREAD

**Issue by tybar** [townteki/townsquare#412]
**Card**
Shadow Walk

**Describe the bug**
I was able to use Shadow Walk to move from Town Square to Town Square.

**To Reproduce**
1. Start a game using a deck with Shadow Walk in it.
2. Attach Shadow Walk to a dude.
3. Move the dude to Town Square (not sure if this can be replicated in other locations yet)
4. Use Shadow Walk, when prompted to select a location to move to, select Town Square.

Observed Behavior: Shadow Walk is used. You should not be allowed to move to the location you're in with the card.

**Comment by mmeldo** [comment]
There are many instances where game "allows" to do something that is not according to rules, and movement to the same location is one of them. It was a conscious decision as I do not want to be too strict and have everything lined up for player.
