### ISSUE TITLE
increased hand size never resets during sundown if persistent effect that was causing it expires

### ISSUE THREAD

**Issue by stopfstedt** [townteki/townsquare#446]
**Describe the bug**

**To Reproduce**
1. Start a game with Randall in your starting posse
2. Observe that hand size is increased to six
3. Move Randall to town square by himself and leave him there by himself
4. Pass through to Sundown
5. Do _not_ discard a card to draw a card
6. Start the new day with six cards in hand. 

This is incorrect. The rulebook states in section 5.4 Sundown:

> All players may choose to discard one card from their play hand, with the Winner choosing first. All players then discard down or refill their play hand to their maximum hand size (normally 5 cards).  

**Screenshots**

![handsize6](https://user-images.githubusercontent.com/1410427/117559274-c3871880-b038-11eb-8be4-7cefe223aa3b.png)

**Additional context**
I encountered this issue when working on implementing #436 and then verified it being a bug in the game engine (and not the card implementation itself) by creating a similar incorrect game state using Randall.

**Comment by mmeldo** [comment]
Thanks for the report. This is not really an effect not being reset, but missing step during the sundown to discard down to the hand size limit. So event though the effect for the increased hand size is no longer there, game engine does not have any logic to force it back to the new hand size. Should be fixed anyway, but currently the circumvention is to manually discard.
