### ISSUE TITLE
Wylie Jenks crashes game

### ISSUE THREAD

**Issue by AaronSchnabel** [townteki/townsquare#482]
**Card**
Wylie Jenks

**Describe the bug**
Law Dogs had Wylie Jenks in posse. Sloane Gang had 2 wanted dudes in posse. When wanted Allie Hensman left play (was discarded to cover a casualty) the game crashed. There was a second wanted dude in the SG posse.

**Additional context**
2021-05-17T17:42:09.083Z - error:  message=Cannot read property 'isWanted' of undefined, stack=TypeError: Cannot read property 'isWanted' of undefined
    at /home/aaron/townsquare/townsquare/server/game/cards/02.1-NTNR/WylieJenks.js:18:90
    at /home/aaron/townsquare/townsquare/server/game/gamesteps/shootout/shootoutposse.js:97:102
    at Array.filter (<anonymous>)

**Comment by mmeldo** [comment]
It looks like there can be a situation when dude is still in posse, but already out of play so the `findCardInPlayByUuid` does not find it and returns null.
Condition to fix is in `ShootoutPosse.getDudes()`:
```
return this.posse.map(dudeUuid => this.player.findCardInPlayByUuid(dudeUuid)).filter(card => condition(card));
```
