### ISSUE TITLE
"blank only traits" ability effect needed. 

### ISSUE THREAD

**Issue by stopfstedt** [townteki/townsquare#680]
see the text on "As Nature and God Intended"

> All Weapons lose their bullet bonuses, traits, and Shootout abilities until the end of this round of the shootout.

that effect should leave abilities other than shootout abilities, like cheatin' resolutions, intact.

however there is currently no way to partially blank cards described in this manner - we only have ways to _fully_ blank cards, and to blank cards excluding keywords.

what's needed is a mechanism that allows for blanking of traits only, card abilities can be selectively turned off by adding other ability effects.

this will require changes to `BaseCard` and `Cardaction::meetsRequirements()`, possibly other places as well.

**Comment by stopfstedt** [comment]
refs #679

**Comment by mmeldo** [comment]
The mechanism to blank only traits was implemented. I have updated also chatcommands to be able to do a specific type of blank and used it for testing (tested `persistentEffect` and `trait reactions`). 
The best approach would be to merge this so you can use it for the #679 and also test it there.
