### ISSUE TITLE
The Orphanage does not affect all deeds with Control >= 2

### ISSUE THREAD

**Issue by AaronSchnabel** [townteki/townsquare#702]
**Card**
The Orphanage

**Describe the bug**
The Orphanage does not properly reduce control or increase production on all deeds with control >= 2

**To Reproduce**
1. Purchase The Orphanage
2. Have some deeds with 2 or more control points on the board
3. Use The Orphanage's ability

**Screenshots**
![orphanage bug](https://user-images.githubusercontent.com/6004301/126677784-40bd753b-bf39-46ad-acee-be0f7d60420b.png)

**Additional context**
I haven't tested all the deeds, but the Undertaker and The Mayor's Office both kept their full control after The Orphanage was used. 1st Baptist Church had it's control reduced to 1 but there is no indication on any deed that their production was increased at all. When I finished the day and went through the upkeep phase, neither player received any extra production.

**Comment by mmeldo** [comment]
This was a tricky one. Problem with Orphanage is that it affects deeds with 2 or more CP, and effect is that it gives penalty -1 CP. That resulted in a loop effect applications for deeds with 2 CP. First, effect was applied and CP was changed to 1, but then the effect condition was no longer valid so it was unapplied and CP was changed back to 2. But then, the condition was again valid ... I guess you see the pattern. In the end, the loop was broken (not sure why), and it could end with the effect applied or not for control (that is why some deeds were affected and some not), but it never reapplied for production.
_Solution_: When checking for control, do not take the Orphanage effect into account.
