### ISSUE TITLE
The Fourth Ring React happens before the pull

### ISSUE THREAD

**Issue by tybar** [townteki/townsquare#849]
**Card**
The Fourth Ring

**Describe the bug**
The Fourth Ring's React prompt triggers before the player knows if they have succeeded the pull or not.

**To Reproduce**
1. Start a game with one player using The Fourth Ring outfit card and at least one hex.
2. Use an ability on a Hex that is outside of your home.
3. The prompt happens prior to the user getting the pull information, so they do not know if the pull has succeeded or not.

**Screenshots**
I did not grab a screenshot, but can if needed.

**Additional context**
I don't think any of my spell pulls failed after the react was used, so I don't know if it's just that the player hasn't been informed, or if the react is being triggered before the pull itself.

**Comment by mmeldo** [comment]
The Fourth Ring reacts only if your pull succeeds, so it triggers it after your pull. That your pull was done can be seen in the "Played/Pulled" pile. There you will see the card that was pulled. The message will be issued afterwards, but that is just informational. I do not really think it is such an issue that warrants reworking the ability resolution engine.

**Comment by mmeldo** [comment]
Of course, if it would be simple change, I would do it.
