### ISSUE TITLE
Old Marge's Manor prompts when inventing at Noon

### ISSUE THREAD

**Issue by tybar** [townteki/townsquare#907]
**Card**
Old Marge's Manor/William Specks

**Describe the bug**
When inventing at Noon, Old Marge's Manor prompts you to reduce the inventing cost if using William Specks' ability.

**To Reproduce**
1. Have a William Specks.
2. Have Old Marge's Manor with at least one ghost rock on it.
3. Attempt to invent a gadget that costs at least 3 ghost rock (so that Specks' ability doesn't pay the whole amount. I used The Devil's Six Gun).
4. Old Marge's Manor prompt displays, offering to use its ghost rock.

**Comment by tybar** [comment]
Note that I just tried to recreate this, and found it was explicitly when using William Specks' ability...updating the bug accordingly.

**Comment by mmeldo** [comment]
I do not believe it is only with Specks. I completely missed it should be used during shootout. It should incorrectly work also with Mechanical Horse.
