### ISSUE TITLE
Unable to create account, error occurred activating

### ISSUE THREAD

**Issue by edwardc4** [townteki/townsquare#963]
Username=EdwardC4

**Describe the bug**
Registered to play doomtown online.  got the activation email, after clicking it get the following:
 An error occured activating your account, check the url you have entered and try again. 

**To Reproduce**
tried on firefox, chrome, internet explorer, edge.  all same error.

**Screenshots**
![image](https://user-images.githubusercontent.com/90853346/133634814-de5d3e86-56f6-4eb3-a9d3-12e753b2f9a5.png)

**Additional context**

**Comment by mmeldo** [comment]
Have you tried both links from the email? One unfortunately does not work. There is issue opened for that. If even the second one does not work for you let us know here and I will activate manually.

**Comment by edwardc4** [comment]
http://doomtown.online%29./

the first link redirects me there.

If it helps here's the full email:


Hi,



Someone, hopefully you, has requested an account to be created on Doomtown Online (https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fu21391870.ct.sendgrid.net%2Fls%2Fclick%3Fupn%3DaBRntLNy3mC07uS57YOwqlD6E-2BZwDNxz5L4nkPSpybOmWaxVCMUMxA06-2BBqH-2FE8M_5og_3BrlSpt-2BfcnedygkauoWIDljdJFdeygI6ckica1zjtnCkXU8q42qImciQpXEz3G6MGm2UoWu3ocOikIcMPV1bRzd-2BErDft76lZG5liCatDw0LDjLxEWN3tjvor9semcWAb8EQ5YzKi0slV-2FJPv1Kdp67Mt6tBee0-2FnXfd8zH6-2FkSVtocu32nsMTMJIdgNQPjfBwN9jgxOuOLYGx4bv-2FHhg-3D-3D&amp;data=04%7C01%7Ceclifton%40insp.com%7C9a9c571391f2427e734208d9791d7f7a%7C3da2778b8fac4742832dd1d32c7936f0%7C0%7C0%7C637673991369159842%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000&amp;sdata=httK1y0LX5wwiC5C0sYq4VZpCUwkyEUkaS%2Fyk7TvbMs%3D&amp;reserved=0  If this was you, click this link https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fu21391870.ct.sendgrid.net%2Fls%2Fclick%3Fupn%3DaBRntLNy3mC07uS57YOwqs4Fyy1nDLeYiineaj9qoenT6A2tQ66mK1VftAR0k5G27oCUoVScsqS8YsswQZt3RF-2BabZvp5-2F3adBDzq8TQYTJmHc0u2sex5dMbXm95onee7B1K7-2BWqFbNu0RhJiynfE8lltMMjsLFC5hub0hOESZjoUBecz6-2F4pOtDoIQ08evbjic4zRb2YjB8GEGIvKeuk6KPY0luh0swMGIoRYgMGh9-2F2GdoL3wk8sLekdRwebBCks8csQ6TzS9PuTAYyXC9RQ-3D-3DmB7K_3BrlSpt-2BfcnedygkauoWIDljdJFdeygI6ckica1zjtnCkXU8q42qImciQpXEz3G6XAlEcjZjOhdvBglGYDnKJT2TR9iUfAFrbF4BcOoaUrCWBtbbIBDSzbE-2B0AeXUpxadM9WPsOAeHUd-2Buh50WMwjLoAa3pKw8yAoWoS7daJBjBAs-2Bvu4dU2hR0aNBU-2FRYHFu-2BVP-2BJsuKQNDaNb4WR4ufA-3D-3D&amp;data=04%7C01%7Ceclifton%40insp.com%7C9a9c571391f2427e734208d9791d7f7a%7C3da2778b8fac4742832dd1d32c7936f0%7C0%7C0%7C637673991369159842%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000&amp;sdata=M%2BxE22en9E9t0tuSYqZWEY21itwgTp6nIO5t7dw19Ps%3D&amp;reserved=0 to complete the process.



If you did not request this please disregard this email.

Kind regards,



Doomtown Online team

**Comment by mmeldo** [comment]
But have you tried the second link (starting after "If this was you, click this link")? Because if I remember correctly that should be the one to verify the account.

**Comment by edwardc4** [comment]
Yup it’s the one that failed

Edward Clifton
IT Systems Administrator
3000 World Reach Drive
Indian Land SC, 29707
Office: (803) 578-1031
Cell: (803) 415-0843

On Sep 16, 2021, at 12:01 PM, Milan M2 ***@***.***> wrote:

﻿

But have you tried the second link (starting after "If this was you, click this link")? Because if I remember correctly that should be the one to verify the account.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftownteki%2Ftownsquare%2Fissues%2F963%23issuecomment-921031463&data=04%7C01%7CEclifton%40insp.com%7Cc68a4a08a2fb4d0a398d08d9792b4c82%7C3da2778b8fac4742832dd1d32c7936f0%7C0%7C0%7C637674049154438804%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=XCleuQ8xeXomn5%2FqNY78HSfYY%2FRGAXjwcP%2FbYva4DIY%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAVVE7YQLAFCO3GBTXXWHVPTUCIIG7ANCNFSM5EE6MREA&data=04%7C01%7CEclifton%40insp.com%7Cc68a4a08a2fb4d0a398d08d9792b4c82%7C3da2778b8fac4742832dd1d32c7936f0%7C0%7C0%7C637674049154448797%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=0o%2FBrLpSbpZkBGaGu4cxopie66TN5lc7%2BjfW6ecxwcY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CEclifton%40insp.com%7Cc68a4a08a2fb4d0a398d08d9792b4c82%7C3da2778b8fac4742832dd1d32c7936f0%7C0%7C0%7C637674049154448797%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2FGcclJE9r8ASRrJb8LOYoHT5Ooj9oKoOCW25SH5rPl8%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CEclifton%40insp.com%7Cc68a4a08a2fb4d0a398d08d9792b4c82%7C3da2778b8fac4742832dd1d32c7936f0%7C0%7C0%7C637674049154458795%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=y3YPCimGUDr560%2BwPaCPSMZCMRH0WcX7HHmTjKxsubs%3D&reserved=0>.

**Comment by mmeldo** [comment]
Did you try to log in? Because your account says it is already verified.

**Comment by edwardc4** [comment]
Welp, now it is working.  I'll take it but earlier it was giving me that error

Thank you!

**Comment by mmeldo** [comment]
Glad it is working :) and I hope you will enjoy the site.
